#!/bin/bash
#Author and Maintained by : Ghanshyam Dusane
#Variables

dbhost=""
dbusername=""
dbpassword=""
dbname="scheduler"
dat=`date +%F`

runbookid=""
ENV=""

SUBJECT="";
SENDGRIDAPIUSER=""
SENDGRIDAPIPASSWORD=""
EMAIL_TO=""
FROM_EMAIL=""
FROM_NAME=""

mysql -h $dbhost -u $dbusername -p$dbpassword -e "use scheduler; select * from runbook_instance where startedat LIKE '$dat%' and runbookid LIKE '$runbookid' ORDER BY endat DESC LIMIT 1;" > /tmp/queryop
query=`cat /tmp/queryop| grep FAILED | wc -l`

if [ "$query" -gt 0 ] ;then

        echo "sending mail"
        instanceid=`cat /tmp/queryop | grep : | awk '{print $1}'`
        runbookid=`cat /tmp/queryop | grep : | awk '{print $2}'`
        startedat=`cat /tmp/queryop | grep : | awk '{print $3 " " $4}'`
        startdate=`cat /tmp/queryop | grep : | awk '{print $3 "-" $4}'`
        endat=`cat /tmp/queryop | grep : | awk '{print $5 " " $6}'`
        status=`cat /tmp/queryop | grep : | awk '{print $7}'`
        SUBJECT="$startdate-$ENV-DataPipeline-Failed-$runbookid";
        mysql -h $dbhost -u $dbusername -p$dbpassword -e "use scheduler; select * from runbook_instance_details where runbook_instance_id=$instanceid;" > /tmp/queryrunbookid
        stepname=`cat /tmp/queryrunbookid | grep FAILED | awk '{print $11}'`

        curl https://api.sendgrid.com/api/mail.send.json \
        -F to=$EMAIL_TO -F subject=$SUBJECT \
        -F text="PipelineReporting" --form-string html="<h1>$ENV : Data Pipeline $runbookid failed</h1><table border="1"><tr><th>instanceid</th><th>runbookid</th><th>startedat</th><th>endat</th><th>status</th></tr><tr><td>$instanceid</td><td>$runbookid</td><td>$startedat</td><td>$endat</td><td>$status</td></tr></table><h4> Note : Due to flow <u> $stepname </u> pipeline $runbookid failed<h4>" \
        -F from=$FROM_EMAIL -F api_user=$SENDGRIDAPIUSER -F api_key=$SENDGRIDAPIPASSWORD

        rm -rf /tmp/queryop
        rm -rf /tmp/queryrunbookid
else
echo "Everyting is okay"
fi
